In [1]:
import numpy as np
from numpy import linalg as LA
import random

a= 4

def d(p1,p2,q):
    t=np.dot((p2-p1),(q-p1))/(LA.norm(p2-p1)**2)
    if t<0:
        x=p1
    elif t>1:
        x=p2
    else:
        x=(p2-p1)*t+p1
    return x

def dlist(grafo,punto):
    return [d(grafo[i],grafo[i+1],punto) for i in range(0,len(grafo)-1)]  

def nodelenght(i,j,grafo):
    lenght=0
    if i<j:
        for i in range(i,j):
            lenght+=LA.norm(grafo[i+1]-grafo[i])
    return lenght

def updown(p1,p2,grafo): #p1 y p2 es de donde sale y quiere llegr o puntos del grafo 
    
    bajadas=dlist(grafo,p2) #Puntos del grafo que estan mas cerca de p2
    subidas=dlist(grafo,p1) #lo mismo pero con p1

    out=[] #El return
    
    db=[LA.norm(i-p2) for i in bajadas] #Distancia de las bajadas entre dos aristas
    dbo=[[db[i],i] for i in range(0,len(db))] #Distancia de las subidas entre dos aristas y su indice, 1er arista
    dbo.sort() #CUAL ES EL CRITERIO PARA ORDENAR ? 

    ds=[LA.norm(i-p1) for i in subidas]
    dso=[[ds[i],i] for i in range(0,len(ds))] 
    dso.sort()    

    ilb=[dbo[i][1] for i in range(0,len(db))] # Me va a tirar los indices de los 3 primeros que estan mas cerca de la bjada
    ils=[dso[i][1] for i in range(0,len(db))] # Lo mismo pero para la subida

    recorrido=[] #Que es recorrido ?
    lenght=0 #Que es lenght ?

    for i in range(0,len(ilb)): #Recorro los indices que me quedo en ilb
        for j in range(0,len(ils)): #Recorro los indices que me quedo en ils
            m=ils[j] 
            n=ilb[i]
            ps=subidas[m]
            pb=bajadas[n]            
            if (n==m) and (LA.norm(grafo[n+1]-pb)) <= (LA.norm(grafo[m+1]-ps)): #Si se sube y baja en el mismo tramo
                out.append([ps,pb])
                lenght=LA.norm(pb-ps)
                recorrido.append(lenght)
            elif ilb[i]>ils[j]:
                out.append([ps,pb])    
                lenght=LA.norm(ps-grafo[m+1])+nodelenght(m+1,n+1,grafo)-LA.norm(grafo[n+1]-pb)
                recorrido.append(lenght)
            lenght=0
    return tuple([out,recorrido])

def walkdistance(ps,pb,pi,pf):
    """ walkdistance toma 4 vectores y les toma la norma del taxista, agarra vectores no coordenadas """
    c1=int(abs(ps[0]-pi[0])+abs(ps[1]-pi[1]))
    c2=int(abs(pb[0]-pf[0])+abs(pb[1]- pf[1]))
    return [c1,c2,c1+c2]

def uds(p1,p2,grafo):
    """Decide con algun criterio cual es la mejor opcion de updown, p1 y p2 no son necesariamente puntos del grafo """
    paradas=updown(p1,p2,grafo)[0]
    dbus=updown(p1,p2,grafo)[1]
    camina=[walkdistance(i[0],i[1],p1,p2) for i in paradas]
#    a = 5 # Esta es el tiempo relativo cuando vamina y anda en cole

    if range(len(dbus) != 0):
        ddbus=[dbus[i] + (a)*camina[i][2] for i in range(len(dbus))] # a es el tiempo x cuadra
        i=ddbus.index(min(ddbus))
        return tuple([ddbus[i],a * LA.norm(p2-p1,1)] ) #el  elemento [0] es el tiempo que tarda en bondi y el [1]  caminando
    else:
        return tuple([a*LA.norm(p2-p1,1),a*LA.norm(p2-p1,1)]) #Si no hay paradas posibles que te minimizen
                                                         # anda caminando

def toptimo(p1,p2,grafo):
    """Me dice cual es el tiempo optimo de viaje"""
    return min(uds(p1,p2,grafo))
#Esta cosa me devuelve el tiempo minimo que tarda entre dos puntos 


def selector(p1,p2,gragrafofo):
    Tiempos = []
    D=[]
    for i in range(0,len(gragrafofo)):
        D =  toptimo(p1,p2,gragrafofo[i])
        Tiempos.append(D)

    tmin = min(Tiempos)
    b = Tiempos.index(tmin) #Este te devuelve el primer minimo que encuentra 
    return(b,tmin) #Retorna el num de grafo que se toma y el tiempo que tarda cuando viaja optimo

def tot(grafo): # Poneme los limites de la ciudad, de alguna forma de acá saco el promedio
    total = 0
    for x1 in range(-1,0):
        for y2 in range(44,61):
            for y1 in range(44,45):
                for x2 in range(-1,16):
                    taux = toptimo(np.array([x1,y1]),np.array([x2,y2]),grafo)
                    total = total + taux
    return (total)

e1 = np.array([1,0])
e2= np.array([0,1])

def optimizador(grafo):
    g1= np.array([grafo[0],grafo[1]+e1])
    g2= np.array([grafo[0],grafo[1]+e2])
    g3= np.array([grafo[0],grafo[1]-e1])
    g4= np.array([grafo[0],grafo[1]-e2])
    g5= np.array([grafo[0]+e1,grafo[1]])
    g6= np.array([grafo[0]+e2,grafo[1]])
    g7= np.array([grafo[0]-e1,grafo[1]])
    g8= np.array([grafo[0]-e2,grafo[1]])
    g9= np.array([grafo[0]+e1+e2,grafo[1]])
    g10= np.array([grafo[0]-e1-e2,grafo[1]])
    g11= np.array([grafo[0]-e1+e2,grafo[1]])
    g12= np.array([grafo[0]+e1-e2,grafo[1]]) 
    g13= np.array([grafo[0],grafo[1]+e2+e1])
    g14= np.array([grafo[0],grafo[1]-e2-e1])
    g15= np.array([grafo[0],grafo[1]+e2-e1])
    g16= np.array([grafo[0],grafo[1]-e2+e1])
    
    
    lista = [] #Lo que voy a minimzar
    grafos = []

    lista.append(tot(grafo))
    lista.append(tot(g1))
    lista.append(tot(g2))
    lista.append(tot(g3))
    lista.append(tot(g4))
    lista.append(tot(g5))
    lista.append(tot(g6))
    lista.append(tot(g7))
    lista.append(tot(g8))
    lista.append(tot(g9))
    lista.append(tot(g10))
    lista.append(tot(g11))
    lista.append(tot(g12))
    lista.append(tot(g13))
    lista.append(tot(g14))
    lista.append(tot(g15))
    lista.append(tot(g16))
    
    
    grafos.append(grafo)
    grafos.append(g1)
    grafos.append(g2)
    grafos.append(g3)
    grafos.append(g4)
    grafos.append(g5)
    grafos.append(g6)
    grafos.append(g7)
    grafos.append(g8)
    grafos.append(g9)
    grafos.append(g10)
    grafos.append(g11)
    grafos.append(g12)
    grafos.append(g13)
    grafos.append(g14)
    grafos.append(g15)
    grafos.append(g16)

#    print(lista)
    tn = min(lista)
#    print(tn)
    indice = lista.index(tn)
#    print(indice)
    return(grafos[indice])



In [2]:
p1=np.array([-1,44])
p2=np.array([-1,45])
q = np.array([2,50])
grafo=np.array([[7,60],[7,44]])
grafo1=np.array([[-1,44],[14,60]])
grafo2=np.array([[-1,44],[15,61]])
grafo4=np.array([[-1,44],[14,59]])
gragrafofo = np.array([grafo2,grafo])
# gragrafofo es un vector de grafos

In [3]:
grafo=np.array([[-1,44],[14,59]])
print(grafo)
print()

for j in range(0,10):
    grafo = optimizador(grafo)
    print(grafo)
    print()

# print(tot(grafo),tot(np.array([[-1,44],[12,59]])),tot(np.array([[-1,44],[13,58]])))
#grafo = np.array([grafo[0]+e2+e1,grafo[1]])

#tot([grafo[0],grafo[1]])
#tot(np.array([grafo[0]+e2+e1,grafo[1]]))

[[-1 44]
 [14 59]]

[[-1 44]
 [15 59]]

[[-2 44]
 [15 59]]

[[-2 44]
 [16 60]]

[[-2 44]
 [17 61]]

[[-2 44]
 [17 61]]

[[-2 44]
 [17 61]]

[[-2 44]
 [17 61]]

[[-2 44]
 [17 61]]

[[-2 44]
 [17 61]]

[[-2 44]
 [17 61]]



In [26]:
#ACA TENGO UN ERROR Y NO SE PORQUE, ESTOS DOS NUMEROS ME TIENEN QUE DAR LO MISMO

print(d(np.array([-1,44]),np.array([14,60]),np.array([-1,45])))
print(d(np.array([-1,44]),np.array([15,61]),np.array([-1,45])))

[-0.5010395  44.53222453]
[-0.50091743 44.53027523]


In [29]:
p1= np.array([-1,44])
p2= np.array([14,60])
q = np.array([-1,60])
np.dot((p2-p1),(q-p1))

256